name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag micheledinelli/aculei-be:latest

      - name: List local Docker images
        run: docker images

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "micheledinelli" --password-stdin docker.io

      - name: Push Docker image
        run: docker push micheledinelli/aculei-be:latest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Triggering deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"
